config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: :logout
end

app/models/profile.rb
class Profile < OpenStruct
  include ActionView::Helpers::DateHelper

  def self.service(user)
    GithubService.new(user.oauth_token)
  end

  def self.find_by(user)
    temp_profile_hash = Profile.service(user).profile_hash(user.screen_name)
    Profile.new(temp_profile_hash)
  end

  def join_date(user)
    creation = Profile.find_by(user).created_at.to_time
    creation.strftime("Joined on %b %d, %Y")
  end

  def starred_count(user)
    starred = Profile.service(user).starred_hash(user.screen_name)
    starred.length
  end

  def owner_repos(user)
    temp_owner_repos_arr = Profile.service(user).owner_repos_hash(user.screen_name)
    temp_owner_repos_arr.map do |owner_repo_hash|
      Profile.new(owner_repo_hash)
    end
  end

  def member_repos(user)
    temp_member_repos_arr = Profile.service(user).member_repos_hash(user.screen_name)
    temp_member_repos_arr.map do |member_repo_hash|
      Profile.new(member_repo_hash)
    end.take(5)
  end

  def all_repos_sorted(user)
    temp_repos_arr = Profile.service(user).sorted_repos_with_contributions_hash(user.screen_name)
    temp_repos_arr.map do |repo_hash|
      Profile.new(repo_hash)
    end
  end

  def time_ago(repo)
    time_ago_in_words(repo.updated_at.to_time)
  end

  def all_orgs(user)
    temp_orgs_arr = Profile.service(user).orgs_hash(user.screen_name)
    temp_orgs_arr.map do |org_hash|
      Profile.new(org_hash)
    end
  end

  def all_commits(user)
     Profile.service(user).push_events_hash(user.screen_name).find_all do |event|
      event[:type] = "PushEvent"
    end.map do |commits_hash|
      Profile.new(commits_hash)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    user = find_or_create_by(uid: auth_info[:uid])

    user.uid                = auth_info.uid
    user.name               = auth_info.extra.raw_info.name
    user.screen_name        = auth_info.extra.raw_info.login
    user.oauth_token        = auth_info.credentials.token
    user.oauth_token_secret = auth_info.credentials.secret
    user.save

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @profile = Profile.find_by(current_user)
    else
      @profile = Profile.new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def html_url(url)
    url.gsub("api.github.com/orgs/", "github.com/")
  end
end

app/views/home/_profile.html.erb
<p>
  <%= image_tag(profile.avatar_url, class: "profile-avatar")%>
</p>

<div class="basic-info">
  <p>
    <%= profile.name %> <br>
    <%= profile.login %>
  </p>

  <p>
    <%= profile.email %>
  </p>

  <p>
    <%= profile.join_date(current_user)  %>
  </p>
  <p>
    Followers: <%= profile.followers %>
  </p>

  <p>
    Starred: <%= profile.starred_count(current_user) %>
  </p>

  <p>
    Following: <%= profile.following %>
  </p>
</div>

<div class="owner-repositories">
  <h4>Popular repositories</h4>
  <% profile.owner_repos(current_user).each do |repo_name| %>
    <li> <%= link_to repo_name.name, repo_name.html_url %> </li>
  <% end %>
</div>

<div class="member-repositories">
  <h4>Repositories contributed to</h4>
  <% profile.member_repos(current_user).each do |repo_name| %>
    <li> <%= link_to repo_name.full_name, repo_name.html_url %> </li>
  <% end %>
</div>

<div class="all-repositories">
  <h4>Repositories</h4>
  <% profile.all_repos_sorted(current_user).each do |repo_name| %>
    <li> <%= link_to repo_name.name, repo_name.html_url %> <br> Updated <%= profile.time_ago(repo_name) %> ago </li>
  <% end %>
</div>

<div class="organizations">
  <h4>Organizations</h4>
  <% profile.all_orgs(current_user).each do |org| %>
    <%= link_to image_tag(org.avatar_url), html_url(org.url) %> <br>
  <% end %>
</div>

<div class="commits">
  <h4>All Commits</h4>
  <% profile.all_commits(current_user).each do |commit| %>
    <li>
      Repo name: <%= commit.repo[:name] %> <br>
      <% if commit.payload[:commits] %>
        Payload: <%= commit.payload[:commits] %>
      <% else %>
        There are no commits
      <% end %>
    </li>
  <% end %>
</div>

app/views/home/index.html.erb
<% if current_user %>
  <%= render partial: 'home/profile', locals: { profile: @profile } %>
<% else %>
  <p>
    Log in to see some neat stuff
  </p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="nav-bar">
  <% if current_user %>
  Hello, <%= current_user.name %>
  <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
  <%= link_to "Log in with Github", github_login_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApicuriousLt</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-body">

  <%= render partial: 'layouts/navbar' %>
  <div class='container-content'>

    <%= yield %>
  </div>
</div>

</body>
</html>